n=5,r=1,c=0,s=1;
while(r<=n){
    while(s<=n-r){
        process.stdout.write("\t");
        s++;
    }
    s=1;
    while(c<r){
        c++;
        process.stdout.write(c+"\t");   
    }
    c--;
    while(c>=1){
        process.stdout.write(c +"\t");
        c--;
    }
    process.stdout.write("\n");
    r++;
}