n=5,r=1,c=0,s=1;
while(r<=n){
    while(s<=n-r){
        process.stdout.write("\t");
        s++;
    }
    s=s-1;
    //console.log(s);
    c=r;
    u=0;
    while(u<n-s){
        process.stdout.write(c+"\t");
        c++;
        u++;   
    }
    c--;
    while(c>r){
        c--;
        process.stdout.write(c +"\t");
    }
    s=1;
    process.stdout.write("\n");
    r++;
}